import type { Metadata } from "next";
import "./globals.scss";
import RQProvider from "./_components/RQProvider";

export const metadata: Metadata = {
  title: "리액트 쿼리 테스트",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RQProvider>{children}</RQProvider>
      </body>
    </html>
  );
}
