import type { Metadata } from "next";
import "./globals.scss";

export const metadata: Metadata = {
  title: "홈",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<Props>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
